In [1]:
pwd

'C:\\Users\\adamc'

In [2]:
import os
cnt_file=os.path.join('Downloads','nt-10-10-5.xyz')

In [3]:
print(cnt_file)

Downloads\nt-10-10-5.xyz


In [4]:
import numpy
cnt_coords=numpy.genfromtxt(fname=cnt_file,dtype='unicode',skip_header=2)

In [5]:
coords=(cnt_coords[:,1:])

In [16]:
coords=coords.astype(numpy.float)
print(coords)

[[ 6.6318  1.4096  0.    ]
 [ 5.4851  3.9852  0.    ]
 [ 4.5367  5.0385  0.    ]
 [ 2.0951  6.4482  0.    ]
 [ 0.7087  6.7429  0.    ]
 [-2.0951  6.4482  0.    ]
 [-3.39    5.8717  0.    ]
 [-5.4851  3.9852  0.    ]
 [-6.1938  2.7577  0.    ]
 [-6.78    0.      0.    ]
 [-6.6318 -1.4096  0.    ]
 [-5.4851 -3.9852  0.    ]
 [-4.5367 -5.0385  0.    ]
 [-2.0951 -6.4482  0.    ]
 [-0.7087 -6.7429  0.    ]
 [ 2.0951 -6.4482  0.    ]
 [ 3.39   -5.8717  0.    ]
 [ 5.4851 -3.9852  0.    ]
 [ 6.1938 -2.7577  0.    ]
 [ 6.4482  2.0951  1.2298]
 [ 5.8717  3.39    1.2298]
 [ 3.9852  5.4851  1.2298]
 [ 2.7577  6.1938  1.2298]
 [ 0.      6.78    1.2298]
 [-1.4096  6.6318  1.2298]
 [-3.9852  5.4851  1.2298]
 [-5.0385  4.5367  1.2298]
 [-6.4482  2.0951  1.2298]
 [-6.7429  0.7087  1.2298]
 [-6.4482 -2.0951  1.2298]
 [-5.8717 -3.39    1.2298]
 [-3.9852 -5.4851  1.2298]
 [-2.7577 -6.1938  1.2298]
 [-0.     -6.78    1.2298]
 [ 1.4096 -6.6318  1.2298]
 [ 3.9852 -5.4851  1.2298]
 [ 5.0385 -4.5367  1.2298]
 

In [31]:
for i in range(1,198):
    if (coords[i,0]==0.7087) & (coords[i,1]==6.7429) & (coords[i,2]==7.3785):
        print(i)
    if (coords[i,0]==2.0951) & (coords[i,1]==6.4482) & (coords[i,2]==7.3785):
        print(i)

137
138


In [32]:
print(coords[137],coords[138])

[2.0951 6.4482 7.3785] [0.7087 6.7429 7.3785]


In [7]:
bond_coords=(coords[95:97,:])

In [8]:
print(bond_coords)

[[ 6.78   -0.      4.919 ]
 [ 6.6318  1.4096  4.919 ]]


In [9]:
z_vals=bond_coords[0,2]

In [13]:
theta=numpy.linspace(0,numpy.pi/2,10)

In [14]:
print(theta)


[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


In [15]:
r=0.5*numpy.sqrt((6.1938-6.78)**2+(2.7577)**2)
print(r)

1.4096577359416007


In [16]:
def z_eqn(theta):
    z=z_vals+2*r*numpy.sin(0.5*theta)*numpy.cos(0.5*theta)
    return z

In [17]:
z_list=[]
for num in theta:
    new_z=z_eqn(num)
    z_list.append(new_z)
print(z_list)
    
    

[4.919, 5.163784496980349, 5.4011313408868835, 5.6238288679708, 5.82511052656204, 5.998860475317743, 6.139799409966682, 6.2436449722980925, 6.307241867448924, 6.328657735941601]


In [18]:
def z_eqn_(theta):
    z=z_vals-2*r*numpy.sin(0.5*theta)*numpy.cos(0.5*theta)
    return z
z_list_=[]
for num in theta:
    new_z_=z_eqn_(num)
    z_list_.append(new_z_)
print(z_list_)

[4.919, 4.67421550301965, 4.436868659113116, 4.2141711320291995, 4.012889473437959, 3.8391395246822566, 3.6982005900333172, 3.5943550277019067, 3.5307581325510755, 3.5093422640583984]


In [19]:
print(bond_coords)

[[ 6.1938 -2.7577  4.919 ]
 [ 6.78   -0.      4.919 ]]


In [20]:
def line_eq(x1,x2,y1,y2):
    m=(y2-y1)/(x2-x1)
    b=m*(-x2)+y2
    return m,b

In [21]:
m,b=line_eq(6.1938,6.78,-2.7577,0)

In [22]:
print(b)

-31.895609007164797


In [23]:
def distance_xy(theta):
    d=2*r*numpy.sin(0.5*theta)**2
    return d
d_list=[]
for num in theta:
    d=distance_xy(num)
    d_list.append(d)
print(d_list)

[0.0, 0.021415868492676387, 0.08501276364350792, 0.1888583259749183, 0.3297972606238578, 0.5035472093795604, 0.7048288679708002, 0.9275263950547166, 1.1648732389612506, 1.409657735941601]


In [24]:
from scipy.optimize import fsolve
x_list=[]
y_list=[]
for num in d_list:
    def xy_eq(z):
        x=z[0]
        y=z[1]
    
        F=numpy.empty((2))
        F[0]=numpy.sqrt((x-6.1938)**2+(y+2.7577)**2)-num
        F[1]=y-m*x-b
        return F
    zguess=numpy.array([6.1938,-2.7577])
    z=fsolve(xy_eq,zguess)
    x_list.append(z[0])
    y_list.append(z[1])
print(x_list)
print(y_list)

    

[6.1938, 6.198252847592122, 6.211476092847651, 6.233067954150782, 6.262372373721828, 6.298498951600876, 6.34035, 6.386653895991247, 6.436003719125823, 6.4869]
[-2.7577, -2.7367521702408824, -2.67454517017065, -2.5729691280081726, -2.4351103803946033, -2.265157695616284, -2.0682749999999994, -1.8504444746245983, -1.6182847897760466, -1.37885]


In [25]:
print(bond_coords)

[[ 6.1938 -2.7577  4.919 ]
 [ 6.78   -0.      4.919 ]]


In [26]:
theta2=numpy.linspace(numpy.pi,numpy.pi/2,10)
def distance_xy_(theta):
    d=2*r*numpy.sin(0.5*theta)**2
    return d
d_list2=[]
for num in theta2:
    d=distance_xy(num)
    d_list2.append(d)
print(d_list2)

[2.8193154718832014, 2.7978996033905252, 2.734302708239693, 2.6304571459082835, 2.4895182112593432, 2.315768262503641, 2.1144866039124013, 1.8917890768284846, 1.6544422329219506, 1.409657735941601]


In [27]:
x_list_=[]
y_list_=[]
for num in d_list2:
    def xy_eq_(z):
        x=z[0]
        y=z[1]
    
        F=numpy.empty((2))
        F[0]=numpy.sqrt((x-6.1938)**2+(y+2.7577)**2)-num
        F[1]=y-m*x-b
        return F
    zguess=numpy.array([6.78,0])
    z=fsolve(xy_eq_,zguess)
    x_list_.append(z[0])
    y_list_.append(z[1])
print(x_list_)
print(y_list_)

[6.78, 6.775547152407879, 6.76232390715235, 6.74073204584922, 6.711427626278172, 6.675301048399124, 6.63345, 6.587146104008753, 6.537796280874177, 6.4869]
[0.0, -0.020947829759116528, -0.08315482982935035, -0.18473087199182664, -0.3225896196053976, -0.49254230438371555, -0.6894249999999996, -0.9072555253754018, -1.139415210223953, -1.3788499999999997]


In [28]:
print(x_list)
print(x_list_)
print(y_list)
print(y_list_)
print(z_list)
print(z_list_)

[6.1938, 6.198252847592122, 6.211476092847651, 6.233067954150782, 6.262372373721828, 6.298498951600876, 6.34035, 6.386653895991247, 6.436003719125823, 6.4869]
[6.78, 6.775547152407879, 6.76232390715235, 6.74073204584922, 6.711427626278172, 6.675301048399124, 6.63345, 6.587146104008753, 6.537796280874177, 6.4869]
[-2.7577, -2.7367521702408824, -2.67454517017065, -2.5729691280081726, -2.4351103803946033, -2.265157695616284, -2.0682749999999994, -1.8504444746245983, -1.6182847897760466, -1.37885]
[0.0, -0.020947829759116528, -0.08315482982935035, -0.18473087199182664, -0.3225896196053976, -0.49254230438371555, -0.6894249999999996, -0.9072555253754018, -1.139415210223953, -1.3788499999999997]
[4.919, 5.163784496980349, 5.4011313408868835, 5.6238288679708, 5.82511052656204, 5.998860475317743, 6.139799409966682, 6.2436449722980925, 6.307241867448924, 6.328657735941601]
[4.919, 4.67421550301965, 4.436868659113116, 4.2141711320291995, 4.012889473437959, 3.8391395246822566, 3.6982005900333172, 

In [76]:
line98=[]
line99=[]
for num in range (0, len(x_list)):
    x1=str(x_list[num])
    x2=str(x_list_[num])
    y1=str(y_list[num])
    y2=str(y_list_[num])
    z1=str(z_list[num])
    z2=str(z_list_[num])
    l98=F'C  {x1} \t {y1} \t {z1}'
    l99=F'C  {x2} \t {y2} \t {z2}'
    line98.append(l98)
    line99.append(l99) 

In [77]:

for num in range (0,len(line99)):
    line_98=line98[num]
    line_99=line99[num]
    with open(cnt_file,'r') as file:
        new_file_content=""
        for line in file:
            stripped_line=line.strip()
            new_line=stripped_line.replace('C 6.1938         -2.7577        4.9190',line_98)
            new_file_content += new_line +"\n"
    with open('cnt_file_{}.xyz'.format(num),'w+') as file:
        file.write(new_file_content)
    with open('cnt_file_{}.xyz'.format(num),'r') as file:
        new_file_content2=""
        for line in file:
            stripped_line=line.strip()
            new_line_2=stripped_line.replace('C  6.7800         -0.0000        4.9190',line_99)
            new_file_content2 += new_line_2 +"\n"
    with open('cnt_file_{}.xyz'.format(num),'w') as file:
        file.write(new_file_content2)

    

In [35]:
str.split(line98[0])

['C', '6.1938', '-2.7577', '4.919']

In [63]:
for num in range (0,len(line98)):
    new_coords=cnt_coords[0:96,:], str.split(line98[num]), str.split(line99[num])
    new_string=str(new_coords)
    with open('cnt_file_{}.xyz'.format(num),'w+') as file:
        file.writelines(new_string)