In [3]:
import os
cnt_file=os.path.join('nt-10-10-5.xyz')


In [6]:
import numpy
cnt_coords=numpy.genfromtxt(fname=cnt_file,dtype='unicode',skip_header=2)


In [7]:
coords=cnt_coords[:,1:]
coords=coords.astype(numpy.float)
print(coords)

[[ 6.78    0.      0.    ]
 [ 6.6318  1.4096  0.    ]
 [ 5.4851  3.9852  0.    ]
 [ 4.5367  5.0385  0.    ]
 [ 2.0951  6.4482  0.    ]
 [ 0.7087  6.7429  0.    ]
 [-2.0951  6.4482  0.    ]
 [-3.39    5.8717  0.    ]
 [-5.4851  3.9852  0.    ]
 [-6.1938  2.7577  0.    ]
 [-6.78    0.      0.    ]
 [-6.6318 -1.4096  0.    ]
 [-5.4851 -3.9852  0.    ]
 [-4.5367 -5.0385  0.    ]
 [-2.0951 -6.4482  0.    ]
 [-0.7087 -6.7429  0.    ]
 [ 2.0951 -6.4482  0.    ]
 [ 3.39   -5.8717  0.    ]
 [ 5.4851 -3.9852  0.    ]
 [ 6.1938 -2.7577  0.    ]
 [ 6.4482  2.0951  1.2298]
 [ 5.8717  3.39    1.2298]
 [ 3.9852  5.4851  1.2298]
 [ 2.7577  6.1938  1.2298]
 [ 0.      6.78    1.2298]
 [-1.4096  6.6318  1.2298]
 [-3.9852  5.4851  1.2298]
 [-5.0385  4.5367  1.2298]
 [-6.4482  2.0951  1.2298]
 [-6.7429  0.7087  1.2298]
 [-6.4482 -2.0951  1.2298]
 [-5.8717 -3.39    1.2298]
 [-3.9852 -5.4851  1.2298]
 [-2.7577 -6.1938  1.2298]
 [-0.     -6.78    1.2298]
 [ 1.4096 -6.6318  1.2298]
 [ 3.9852 -5.4851  1.2298]
 

In [8]:
for i in range(0,len(coords)):
    if (coords[i,2]==0):
        print(f'H {coords[i,0]} {coords[i,1]} -1.07')
        

H 6.78 0.0 -1.07
H 6.6318 1.4096 -1.07
H 5.4851 3.9852 -1.07
H 4.5367 5.0385 -1.07
H 2.0951 6.4482 -1.07
H 0.7087 6.7429 -1.07
H -2.0951 6.4482 -1.07
H -3.39 5.8717 -1.07
H -5.4851 3.9852 -1.07
H -6.1938 2.7577 -1.07
H -6.78 0.0 -1.07
H -6.6318 -1.4096 -1.07
H -5.4851 -3.9852 -1.07
H -4.5367 -5.0385 -1.07
H -2.0951 -6.4482 -1.07
H -0.7087 -6.7429 -1.07
H 2.0951 -6.4482 -1.07
H 3.39 -5.8717 -1.07
H 5.4851 -3.9852 -1.07
H 6.1938 -2.7577 -1.07


In [9]:
for i in range(0,len(coords)):
    if (coords[i,2]==11.0678):
        print(f'H {coords[i,0]} {coords[i,1]} 12.1378')
              

H -6.4482 2.0951 12.1378
H -6.7429 0.7087 12.1378
H -6.4482 -2.0951 12.1378
H -5.8717 -3.39 12.1378
H -3.9852 -5.4851 12.1378
H -2.7577 -6.1938 12.1378
H -0.0 -6.78 12.1378
H 1.4096 -6.6318 12.1378
H 3.9852 -5.4851 12.1378
H 5.0385 -4.5367 12.1378
H 6.4482 -2.0951 12.1378
H 6.7429 -0.7087 12.1378
H 6.4482 2.0951 12.1378
H 5.8717 3.39 12.1378
H 3.9852 5.4851 12.1378
H 2.7577 6.1938 12.1378
H 0.0 6.78 12.1378
H -1.4096 6.6318 12.1378
H -3.9852 5.4851 12.1378
H -5.0385 4.5367 12.1378


In [4]:
import psi4
psi4.set_output_file('cnth_energy_pbe-6-31G', False)
psi4.set_module_options('scf',{'maxiter': 500})

In [5]:
psi4.set_memory(7.5e9)

7500000000

In [6]:

cnt=psi4.geometry("""
0 1
C  6.7800         0.0000         0.0000
C  6.6318         1.4096         0.0000
C  5.4851         3.9852         0.0000
C  4.5367         5.0385         0.0000
C  2.0951         6.4482         0.0000
C  0.7087         6.7429         0.0000
C  -2.0951        6.4482         0.0000
C  -3.3900        5.8717         0.0000
C  -5.4851        3.9852         0.0000
C  -6.1938        2.7577         0.0000
C  -6.7800        0.0000         0.0000
C  -6.6318        -1.4096        0.0000
C  -5.4851        -3.9852        0.0000
C  -4.5367        -5.0385        0.0000
C  -2.0951        -6.4482        0.0000
C  -0.7087        -6.7429        0.0000
C  2.0951         -6.4482        0.0000
C  3.3900         -5.8717        0.0000
C  5.4851         -3.9852        0.0000
C  6.1938         -2.7577        0.0000
C  6.4482         2.0951         1.2298
C  5.8717         3.3900         1.2298
C  3.9852         5.4851         1.2298
C  2.7577         6.1938         1.2298
C  0.0000         6.7800         1.2298
C  -1.4096        6.6318         1.2298
C  -3.9852        5.4851         1.2298
C  -5.0385        4.5367         1.2298
C  -6.4482        2.0951         1.2298
C  -6.7429        0.7087         1.2298
C  -6.4482        -2.0951        1.2298
C  -5.8717        -3.3900        1.2298
C  -3.9852        -5.4851        1.2298
C  -2.7577        -6.1938        1.2298
C  -0.0000        -6.7800        1.2298
C  1.4096         -6.6318        1.2298
C  3.9852         -5.4851        1.2298
C  5.0385         -4.5367        1.2298
C  6.4482         -2.0951        1.2298
C  6.7429         -0.7087        1.2298
C  5.4851         3.9852         2.4595
C  4.5367         5.0385         2.4595
C  2.0951         6.4482         2.4595
C  0.7087         6.7429         2.4595
C  -2.0951        6.4482         2.4595
C  -3.3900        5.8717         2.4595
C  -5.4851        3.9852         2.4595
C  -6.1938        2.7577         2.4595
C  -6.7800        0.0000         2.4595
C  -6.6318        -1.4096        2.4595
C  -5.4851        -3.9852        2.4595
C  -4.5367        -5.0385        2.4595
C  -2.0951        -6.4482        2.4595
C  -0.7087        -6.7429        2.4595
C  2.0951         -6.4482        2.4595
C  3.3900         -5.8717        2.4595
C  5.4851         -3.9852        2.4595
C  6.1938         -2.7577        2.4595
C  6.7800         -0.0000        2.4595
C  6.6318         1.4096         2.4595
C  3.9852         5.4851         3.6893
C  2.7577         6.1938         3.6893
C  0.0000         6.7800         3.6893
C  -1.4096        6.6318         3.6893
C  -3.9852        5.4851         3.6893
C  -5.0385        4.5367         3.6893
C  -6.4482        2.0951         3.6893
C  -6.7429        0.7087         3.6893
C  -6.4482        -2.0951        3.6893
C  -5.8717        -3.3900        3.6893
C  -3.9852        -5.4851        3.6893
C  -2.7577        -6.1938        3.6893
C  -0.0000        -6.7800        3.6893
C  1.4096         -6.6318        3.6893
C  3.9852         -5.4851        3.6893
C  5.0385         -4.5367        3.6893
C  6.4482         -2.0951        3.6893
C  6.7429         -0.7087        3.6893
C  6.4482         2.0951         3.6893
C  5.8717         3.3900         3.6893
C  2.0951         6.4482         4.9190
C  0.7087         6.7429         4.9190
C  -2.0951        6.4482         4.9190
C  -3.3900        5.8717         4.9190
C  -5.4851        3.9852         4.9190
C  -6.1938        2.7577         4.9190
C  -6.7800        0.0000         4.9190
C  -6.6318        -1.4096        4.9190
C  -5.4851        -3.9852        4.9190
C  -4.5367        -5.0385        4.9190
C  -2.0951        -6.4482        4.9190
C  -0.7087        -6.7429        4.9190
C  2.0951         -6.4482        4.9190
C  3.3900         -5.8717        4.9190
C  5.4851         -3.9852        4.9190
C  6.1938         -2.7577        4.9190
C  6.7800         -0.0000        4.9190
C  6.6318         1.4096         4.9190
C  5.4851         3.9852         4.9190
C  4.5367         5.0385         4.9190
C  0.0000         6.7800         6.1488
C  -1.4096        6.6318         6.1488
C  -3.9852        5.4851         6.1488
C  -5.0385        4.5367         6.1488
C  -6.4482        2.0951         6.1488
C  -6.7429        0.7087         6.1488
C  -6.4482        -2.0951        6.1488
C  -5.8717        -3.3900        6.1488
C  -3.9852        -5.4851        6.1488
C  -2.7577        -6.1938        6.1488
C  -0.0000        -6.7800        6.1488
C  1.4096         -6.6318        6.1488
C  3.9852         -5.4851        6.1488
C  5.0385         -4.5367        6.1488
C  6.4482         -2.0951        6.1488
C  6.7429         -0.7087        6.1488
C  6.4482         2.0951         6.1488
C  5.8717         3.3900         6.1488
C  3.9852         5.4851         6.1488
C  2.7577         6.1938         6.1488
C  -2.0951        6.4482         7.3785
C  -3.3900        5.8717         7.3785
C  -5.4851        3.9852         7.3785
C  -6.1938        2.7577         7.3785
C  -6.7800        0.0000         7.3785
C  -6.6318        -1.4096        7.3785
C  -5.4851        -3.9852        7.3785
C  -4.5367        -5.0385        7.3785
C  -2.0951        -6.4482        7.3785
C  -0.7087        -6.7429        7.3785
C  2.0951         -6.4482        7.3785
C  3.3900         -5.8717        7.3785
C  5.4851         -3.9852        7.3785
C  6.1938         -2.7577        7.3785
C  6.7800         -0.0000        7.3785
C  6.6318         1.4096         7.3785
C  5.4851         3.9852         7.3785
C  4.5367         5.0385         7.3785
C  2.0951         6.4482         7.3785
C  0.7087         6.7429         7.3785
C  -3.9852        5.4851         8.6083
C  -5.0385        4.5367         8.6083
C  -6.4482        2.0951         8.6083
C  -6.7429        0.7087         8.6083
C  -6.4482        -2.0951        8.6083
C  -5.8717        -3.3900        8.6083
C  -3.9852        -5.4851        8.6083
C  -2.7577        -6.1938        8.6083
C  -0.0000        -6.7800        8.6083
C  1.4096         -6.6318        8.6083
C  3.9852         -5.4851        8.6083
C  5.0385         -4.5367        8.6083
C  6.4482         -2.0951        8.6083
C  6.7429         -0.7087        8.6083
C  6.4482         2.0951         8.6083
C  5.8717         3.3900         8.6083
C  3.9852         5.4851         8.6083
C  2.7577         6.1938         8.6083
C  0.0000         6.7800         8.6083
C  -1.4096        6.6318         8.6083
C  -5.4851        3.9852         9.8380
C  -6.1938        2.7577         9.8380
C  -6.7800        0.0000         9.8380
C  -6.6318        -1.4096        9.8380
C  -5.4851        -3.9852        9.8380
C  -4.5367        -5.0385        9.8380
C  -2.0951        -6.4482        9.8380
C  -0.7087        -6.7429        9.8380
C  2.0951         -6.4482        9.8380
C  3.3900         -5.8717        9.8380
C  5.4851         -3.9852        9.8380
C  6.1938         -2.7577        9.8380
C  6.7800         -0.0000        9.8380
C  6.6318         1.4096         9.8380
C  5.4851         3.9852         9.8380
C  4.5367         5.0385         9.8380
C  2.0951         6.4482         9.8380
C  0.7087         6.7429         9.8380
C  -2.0951        6.4482         9.8380
C  -3.3900        5.8717         9.8380
C  -6.4482        2.0951         11.0678
C  -6.7429        0.7087         11.0678
C  -6.4482        -2.0951        11.0678
C  -5.8717        -3.3900        11.0678
C  -3.9852        -5.4851        11.0678
C  -2.7577        -6.1938        11.0678
C  -0.0000        -6.7800        11.0678
C  1.4096         -6.6318        11.0678
C  3.9852         -5.4851        11.0678
C  5.0385         -4.5367        11.0678
C  6.4482         -2.0951        11.0678
C  6.7429         -0.7087        11.0678
C  6.4482         2.0951         11.0678
C  5.8717         3.3900         11.0678
C  3.9852         5.4851         11.0678
C  2.7577         6.1938         11.0678
C  0.0000         6.7800         11.0678
C  -1.4096        6.6318         11.0678
C  -3.9852        5.4851         11.0678
C  -5.0385        4.5367         11.0678
H 6.78 0.0 -1.07
H 6.6318 1.4096 -1.07
H 5.4851 3.9852 -1.07
H 4.5367 5.0385 -1.07
H 2.0951 6.4482 -1.07
H 0.7087 6.7429 -1.07
H -2.0951 6.4482 -1.07
H -3.39 5.8717 -1.07
H -5.4851 3.9852 -1.07
H -6.1938 2.7577 -1.07
H -6.78 0.0 -1.07
H -6.6318 -1.4096 -1.07
H -5.4851 -3.9852 -1.07
H -4.5367 -5.0385 -1.07
H -2.0951 -6.4482 -1.07
H -0.7087 -6.7429 -1.07
H 2.0951 -6.4482 -1.07
H 3.39 -5.8717 -1.07
H 5.4851 -3.9852 -1.07
H 6.1938 -2.7577 -1.07
H -6.4482 2.0951 12.1378
H -6.7429 0.7087 12.1378
H -6.4482 -2.0951 12.1378
H -5.8717 -3.39 12.1378
H -3.9852 -5.4851 12.1378
H -2.7577 -6.1938 12.1378
H -0.0 -6.78 12.1378
H 1.4096 -6.6318 12.1378
H 3.9852 -5.4851 12.1378
H 5.0385 -4.5367 12.1378
H 6.4482 -2.0951 12.1378
H 6.7429 -0.7087 12.1378
H 6.4482 2.0951 12.1378
H 5.8717 3.39 12.1378
H 3.9852 5.4851 12.1378
H 2.7577 6.1938 12.1378
H 0.0 6.78 12.1378
H -1.4096 6.6318 12.1378
H -3.9852 5.4851 12.1378
H -5.0385 4.5367 12.1378

""")


Unoptimized energy using  PBE/6-31G* = 7636.148904774724 Hartrees


In [ ]:
psi4.set_output_file('cnth_opt.dat', False)
psi4.optimize('pbe/6-31G*',molecule=cnt)
psi4.set_output_file('cnth_opt_final.dat', False)
cnt.print_out_in_angstrom()
